keys:
  - &evelyn age1pzn74xh6lknymmrv3hv39cs6zm7nefarx5pf8cgd5flnjsss847s6unxz2
  - &hermes age14ytph87pl9p8metv8zedefmdyg25yvewm3fn7zydqzww2t72gdrqankp4p
  - &mcp-audit  age17h3e72mdug9qmdhhctsuhpxp3m9u3akkadqsvz7hvyzv849knahqpgnd5m
  - &mcp-nats01 age1yttk6cvd6rkc0amztmt9lemlv3e09mc2tfevwd9zr39hqyl4rulqnc5q2r
  - &mcp-nats02 age1ja75kpam44ren20l2p2rh7wpzrprxsj5pjypzjjeejcjn86g6daspg827n
  - &mcp-nats03 age18xa8hvjnrjufyvanw69g7hf029gzkzj5ey0lm5f8p7ejr3qcjq4q9unt0m

creation_rules:
  - path_regex: secrets/host-sops-keys\.ya?ml$
    key_groups:
      - age:
          - *evelyn
  - path_regex: secrets/hermes\.ya?ml$
    key_groups:
      - age:
          - *evelyn
          - *hermes
  - path_regex: secrets/mcp-audit\.ya?ml$
    key_groups:
      - age:
          - *evelyn
          - *mcp-audit
  - path_regex: secrets/nats-operator\.ya?ml$
    key_groups:
      - age:
          - *evelyn
          - *mcp-nats01
          - *mcp-nats02
          - *mcp-nats03
  - path_regex: secrets/mcp-nats01\.ya?ml$
    key_groups:
      - age:
          - *evelyn
          - *mcp-nats01
  - path_regex: secrets/mcp-nats02\.ya?ml$
    key_groups:
      - age:
          - *evelyn
          - *mcp-nats02
  - path_regex: secrets/mcp-nats03\.ya?ml$
    key_groups:
      - age:
          - *evelyn
          - *mcp-nats03
